# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aggiungicliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 500)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 700, 500))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(229, 215, 99, 255), stop:1 rgba(255, 255, 255, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 130, 60, 16))
        self.label.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label.setObjectName("label")
        self.nome = QtWidgets.QLineEdit(self.frame)
        self.nome.setGeometry(QtCore.QRect(140, 130, 113, 21))
        self.nome.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.nome.setObjectName("nome")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 60, 16))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_2.setObjectName("label_2")
        self.cognome = QtWidgets.QLineEdit(self.frame)
        self.cognome.setGeometry(QtCore.QRect(140, 170, 113, 21))
        self.cognome.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.cognome.setObjectName("cognome")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 91, 16))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_3.setObjectName("label_3")
        self.cf = QtWidgets.QLineEdit(self.frame)
        self.cf.setGeometry(QtCore.QRect(150, 220, 161, 21))
        self.cf.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.cf.setObjectName("cf")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 101, 20))
        self.label_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(160, 260, 110, 24))
        self.dateEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 300, 101, 20))
        self.label_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(50, 330, 111, 20))
        self.label_6.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(370, 130, 101, 20))
        self.label_7.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(370, 170, 101, 20))
        self.label_8.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(370, 220, 101, 20))
        self.label_9.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(370, 270, 101, 20))
        self.label_10.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_10.setObjectName("label_10")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(150, 300, 113, 21))
        self.email.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.email.setObjectName("email")
        self.via = QtWidgets.QLineEdit(self.frame)
        self.via.setGeometry(QtCore.QRect(480, 220, 113, 21))
        self.via.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.via.setObjectName("via")
        self.citta = QtWidgets.QLineEdit(self.frame)
        self.citta.setGeometry(QtCore.QRect(480, 130, 113, 21))
        self.citta.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.citta.setObjectName("citta")
        self.cap = QtWidgets.QLineEdit(self.frame)
        self.cap.setGeometry(QtCore.QRect(480, 170, 113, 21))
        self.cap.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.cap.setObjectName("cap")
        self.numerocivico = QtWidgets.QLineEdit(self.frame)
        self.numerocivico.setGeometry(QtCore.QRect(480, 270, 113, 21))
        self.numerocivico.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.numerocivico.setObjectName("numerocivico")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(180, 330, 161, 26))
        self.comboBox.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.annulla = QtWidgets.QPushButton(self.frame)
        self.annulla.setGeometry(QtCore.QRect(370, 410, 113, 32))
        self.annulla.setStyleSheet("")
        self.annulla.setObjectName("annulla")
        self.aggiungi = QtWidgets.QPushButton(self.frame)
        self.aggiungi.setGeometry(QtCore.QRect(510, 410, 113, 32))
        self.aggiungi.setObjectName("aggiungi")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(80, 30, 551, 71))
        font = QtGui.QFont()
        font.setFamily("Bangla MN")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"")
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nome"))
        self.label_2.setText(_translate("Dialog", "Cognome"))
        self.label_3.setText(_translate("Dialog", "Codice fiscale"))
        self.label_4.setText(_translate("Dialog", "Data di nascita"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.label_5.setText(_translate("Dialog", "Email"))
        self.label_6.setText(_translate("Dialog", "Ricezione fattura"))
        self.label_7.setText(_translate("Dialog", "Città"))
        self.label_8.setText(_translate("Dialog", "CAP"))
        self.label_9.setText(_translate("Dialog", "Via"))
        self.label_10.setText(_translate("Dialog", "Numero civico"))
        self.comboBox.setItemText(0, _translate("Dialog", "Cartacea"))
        self.comboBox.setItemText(1, _translate("Dialog", "Posta elettronica"))
        self.annulla.setText(_translate("Dialog", "Annulla"))
        self.aggiungi.setText(_translate("Dialog", "Aggiungi"))
        self.label_11.setText(_translate("Dialog", "Inserisci i dati da aggiungere"))
